version: '3.7'
services:
  store-frontend:
    container_name: via-ecommerse-store-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
      - './public:/app/public'
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - store

networks:
  store: