version: '3.7'
services:
  warehouse-backend-db:
    container_name: via-ecommerse-warehouse-backend-db
    image: mongo:4.4.2
    networks:
      - warehouse-backend

  warehouse-backend-api:
    container_name: via-ecommerse-warehouse-backend-api
    build: .
    depends_on:
      - warehouse-backend-db
    environment:
      MONGODB_URL: mongodb://warehouse-backend-db:27017
      MONGODB_DB_NAME: api
      APP_HOST: 0.0.0.0
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - warehouse-backend

networks:
  warehouse-backend: