version: '3.7'
services:
  store-backend-db:
    container_name: via-ecommerse-store-backend-db
    image: mongo:4.4.2
    networks:
      - store

  store-backend-api:
    container_name: via-ecommerse-store-backend-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - store-backend-db
    environment:
      MONGODB_URL: mongodb://store-backend-db:27017
      MONGODB_DB_NAME: store
      APP_HOST: 0.0.0.0
      WH_API_HOST: host.docker.internal
      WH_API_PORT: 8000
    ports:
      - 127.0.0.1:8100:8100
    networks:
      - store

  store-frontend:
    container_name: via-ecommerse-store-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
    environment:
      VUE_APP_STORE_API_HOST: localhost
      VUE_APP_STORE_API_PORT: 8100
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - store

networks:
  store:
